In [1]:
import nltk
from nltk.corpus import stopwords

In [2]:
# I take a famous speech of A.P.J Abdul Kalam sir as string 
paragraph = '''I have three visions for India. In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds. From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. Yet we have not done this to any other nation. We have not conquered anyone. We have not grabbed their land, their culture and their history and tried to enforce our way of life on them. Why? Because we respect the freedom of others. That is why my FIRST VISION is that of FREEDOM. I believe that India got its first vision of this in 1857, when we started the war of Independence. It is this freedom that we must protect and nurture and build on. If we are not free, no one will respect us.'''

In [3]:
paragraph

'I have three visions for India. In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds. From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. Yet we have not done this to any other nation. We have not conquered anyone. We have not grabbed their land, their culture and their history and tried to enforce our way of life on them. Why? Because we respect the freedom of others. That is why my FIRST VISION is that of FREEDOM. I believe that India got its first vision of this in 1857, when we started the war of Independence. It is this freedom that we must protect and nurture and build on. If we are not free, no one will respect us.'

In [4]:
sentences = nltk.sent_tokenize(paragraph)
len(sentences)
sentences

['I have three visions for India.',
 'In 3000 years of our history people from all over the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture and their history and tried to enforce our way of life on them.',
 'Why?',
 'Because we respect the freedom of others.',
 'That is why my FIRST VISION is that of FREEDOM.',
 'I believe that India got its first vision of this in 1857, when we started the war of Independence.',
 'It is this freedom that we must protect and nurture and build on.',
 'If we are not free, no one will respect us.']

In [5]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    print(words)

['I', 'have', 'three', 'visions', 'for', 'India', '.']
['In', '3000', 'years', 'of', 'our', 'history', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.']
['From', 'Alexander', 'onwards', 'the', 'Greeks', ',', 'the', 'Turks', ',', 'the', 'Moguls', ',', 'the', 'Portuguese', ',', 'the', 'British', ',', 'the', 'French', ',', 'the', 'Dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.']
['Yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.']
['We', 'have', 'not', 'conquered', 'anyone', '.']
['We', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', 'and', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.']
['Why', '?']
['Because', 'we', 'respect', 'the', 'freedom', 'of', 'others', '.']
['That', 'is', 'why', 'my', 'FIRST', 'VISION', 'is

In [6]:
from nltk.stem import PorterStemmer
pstem_sentences = ['']*len(sentences)
stemmer = PorterStemmer()
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word)  for word in words if word not in set(stopwords.words('english'))]
    pstem_sentences[i] = ' '.join(words)
pstem_sentences

['i three vision india .',
 'in 3000 year histori peopl world come invad us , captur land , conquer mind .',
 'from alexand onward greek , turk , mogul , portugues , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'we conquer anyon .',
 'we grab land , cultur histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom other .',
 'that first vision freedom .',
 'i believ india got first vision 1857 , start war independ .',
 'it freedom must protect nurtur build .',
 'if free , one respect us .']

In [7]:
from nltk.stem import WordNetLemmatizer
wnet_lemmatizer = WordNetLemmatizer()
wnet_sentences = ['']*len(sentences)
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
#     words = [wnet_lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    stop_words = [word for word in words if word not in set(stopwords.words('english'))]
    l_words = [wnet_lemmatizer.lemmatize(word) for word in stop_words ]
    wnet_sentences[i] = ' '.join(l_words)
wnet_sentences

['I three vision India .',
 'In 3000 year history people world come invaded u , captured land , conquered mind .',
 'From Alexander onwards Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .',
 'Yet done nation .',
 'We conquered anyone .',
 'We grabbed land , culture history tried enforce way life .',
 'Why ?',
 'Because respect freedom others .',
 'That FIRST VISION FREEDOM .',
 'I believe India got first vision 1857 , started war Independence .',
 'It freedom must protect nurture build .',
 'If free , one respect u .']

<h4>Cleaning the data

In [8]:
import re
data =[]
for i in range(len(wnet_sentences)):
    clean_sen = re.sub('[^a-zA-Z]', ' ', wnet_sentences[i])
    lower_clean_sen = clean_sen.lower()
    words = lower_clean_sen.split()
    data.append(' '.join(words))
data

['i three vision india',
 'in year history people world come invaded u captured land conquered mind',
 'from alexander onwards greeks turks moguls portuguese british french dutch came looted u took',
 'yet done nation',
 'we conquered anyone',
 'we grabbed land culture history tried enforce way life',
 'why',
 'because respect freedom others',
 'that first vision freedom',
 'i believe india got first vision started war independence',
 'it freedom must protect nurture build',
 'if free one respect u']

<h4>Creating bags of word model
    <h5>Counter Vectorizer

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv_features = cv.fit_transform(data)
cv_features.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     

In [10]:
cv_features.shape


(12, 58)

In [11]:
import numpy as np
ncv_features = np.array(cv_features.toarray())
ncv_features

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     

In [12]:
import pandas as pd
cv_df = pd.DataFrame(ncv_features, columns = ['features{}'.format(i) for i in range(ncv_features.shape[1])])
cv_df.head()

features0  features1  features2  features3  features4  features5  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          1          0          0          0          1          0   
3          0          0          0          0          0          0   
4          0          1          0          0          0          0   

   features6  features7  features8  features9  ...  features48  features49  \
0          0          0          0          0  ...           0           0   
1          0          1          1          1  ...           0           0   
2          1          0          0          0  ...           0           1   
3          0          0          0          0  ...           0           0   
4          0          0          0          1  ...           0           0   

   features50  features51  features52  features53  features54  features55  \
0           1           0           0           0           0           0   
1           0           0           0           0           0           1   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           1           0           0   

   features56  features57  
0           0           0  
1           1           0  
2           0           0  
3           0           1  
4           0           0  

[5 rows x 58 columns]

<h4>Creating TF-IDF model

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer()
tf_features = tfv.fit_transform(data).toarray()
ntf_features = np.array(tf_features)
ntf_features[0:3] 

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.56467934, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.65751246, 0.        , 0.        , 0.        ,
        0.49881319, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.31291783, 0.31291783, 0.26873746,
        0.        , 0.        , 0.        , 0.        , 0.        ,
   

In [14]:
ntf_features.shape

(12, 58)

In [15]:
tf_df = pd.DataFrame(ntf_features, columns = ['feature{}'.format(i) for i in range(ntf_features.shape[1])])
tf_df.head()

feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0   0.00000  0.000000       0.0       0.0   0.00000       0.0   0.00000   
1   0.00000  0.000000       0.0       0.0   0.00000       0.0   0.00000   
2   0.27735  0.000000       0.0       0.0   0.27735       0.0   0.27735   
3   0.00000  0.000000       0.0       0.0   0.00000       0.0   0.00000   
4   0.00000  0.635627       0.0       0.0   0.00000       0.0   0.00000   

   feature7  feature8  feature9  ...  feature48  feature49  feature50  \
0  0.000000  0.000000  0.000000  ...        0.0    0.00000   0.498813   
1  0.312918  0.312918  0.268737  ...        0.0    0.00000   0.000000   
2  0.000000  0.000000  0.000000  ...        0.0    0.27735   0.000000   
3  0.000000  0.000000  0.000000  ...        0.0    0.00000   0.000000   
4  0.000000  0.000000  0.545884  ...        0.0    0.00000   0.000000   

   feature51  feature52  feature53  feature54  feature55  feature56  feature57  
0        0.0        0.0   0.000000        0.0   0.000000   0.000000    0.00000  
1        0.0        0.0   0.000000        0.0   0.312918   0.312918    0.00000  
2        0.0        0.0   0.000000        0.0   0.000000   0.000000    0.00000  
3        0.0        0.0   0.000000        0.0   0.000000   0.000000    0.57735  
4        0.0        0.0   0.545884        0.0   0.000000   0.000000    0.00000  

[5 rows x 58 columns]